---
title: "Resultado Primario"
author: "tiago"
date: "4 de dezembro de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(readxl)
library(scales)
library(ggrepel)
library(ipeaData)
library(extrafont)
library(gganimate)
library(RColorBrewer)
library(ckanr)
library(zoo)

tema <- function(){
    theme_minimal() +
    theme(
      text = element_text(family = "Open Sans", colour = "grey20"),
      axis.text = element_text(family = "Open Sans", colour = "grey20", size = 16),
      title = element_text(face = "bold"), # size para o Shiny
      plot.subtitle = element_text(family = "Open Sans Condensed", face = "plain", size = 20, color = "#1E4C7A"),
      plot.caption = element_text(face = "italic"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      legend.text = element_text(size = 18),
      legend.title = element_text(size = 18),
      axis.ticks = element_line(size = 0.5),
      axis.ticks.length = unit(.25, "cm"),
      axis.title = element_text(size = 16),
      legend.position = 'bottom')
  }

```


## Resultado primário

```{r importa, echo=FALSE}
# recurso_TT <- resource_show(id="527ccdb1-3059-42f3-bf23-b5e3ab4c6dc6",
#                             url="https://apickan.tesouro.gov.br/ckan")
# download.file(recurso_TT$url, destfile = "./rtn.xlsx", mode = 'wb' )
tabela <- read_excel("rtn.xlsx", sheet = "1.1-A", skip = 4)
```

## Tratando os dados

```{r}

meses <- c("Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro")

serie <- tabela %>% 
  rename(rotulos = 1) %>%
  filter(str_detect(rotulos, "VI. PRIMÁRIO GOVERNO") |
           str_detect(rotulos, "Deflator - IPCA")) %>%
  mutate(rotulos = c("Valor", "IPCA")) %>%
  gather(-1, key = "Periodo", value = "Valores") %>%
  spread(key = rotulos, value = Valores) %>%
  mutate(Valor = as.numeric(Valor),
         IPCA = as.numeric(IPCA),
         Periodo = as.Date(as.numeric(Periodo), origin = "1899-12-30"),
         Ano = lubridate::year(Periodo),
         Mes = lubridate::month(Periodo),
         Valor_12m = zoo::rollapply(Valor, width = 12, FUN = sum, fill = NA, align = 'right'),
         Resultado = ifelse(Valor_12m > 0, "Positivo", "Negativo"),
         Data = paste0(Ano, " - ", meses[Mes])) %>%
  filter(!is.na(Valor_12m)) %>%
  filter(Periodo >= "2006-01-01") # para ficar igual à série da dívida


```

Para poder fazer um gráfico de area, preciso segmentar o gráfico em grupo contíguos. Ou seja, agrupar as sequencias de negativos e positivos.

```{r}
palavra_chave <- "Grupo_"
i <- 1
ultimo_grupo <- paste0("Grupo_", i)
grupo <- c(ultimo_grupo)

vetor <- serie$Resultado

for (j in 2:length(vetor)) {
  if (vetor[j] != vetor[j-1]) {
    i <- i+1
    ultimo_grupo <- paste0("Grupo_", i)
  }
  grupo <- c(grupo, ultimo_grupo)
}

serie$Grupos <- grupo
```

Plotando

```{r}
vermelho <- brewer.pal(3, name = "Set1")[1]
azul <- brewer.pal(3, name = "Set1")[2]
verde <- brewer.pal(3, name = "Set1")[3]

vermelho_claro <- "#ee7576"
azul_claro     <- "#87b1d4"

grafico_linha <- ggplot(serie, aes(x = Periodo, y = Valor_12m, color = Resultado, fill = Resultado, group = 1)) +
  geom_area(aes(group = Grupos)) +
  geom_line(size = 1) + 
  geom_point(size = 3, shape = 21, fill = "#f0f5f7") +
  geom_hline(yintercept = 0, color = '#f0f5f7', size = 1) +
  scale_color_manual(values = c("Negativo" = vermelho, "Positivo" = azul)) +
  scale_fill_manual(values = c("Negativo" = vermelho_claro, "Positivo" = azul_claro)) +  
  scale_x_date(date_breaks = "1 years", 
               date_labels = "%Y", 
               limits = c(as.Date("2006-01-01"), NA), #"1997-12-01"
               expand = expand_scale(mult = c(.04, .04))) +
  coord_cartesian(clip = 'off') + 
  labs(x = NULL, y = NULL) +
  geom_text(aes(x = Periodo + 200,
                label = format(round(Valor_12m/1000,0), 
                                      big.mark = ".", 
                                      decimal.mark = ",")),
            size = 7, fontface = 'plain', family = "Open Sans SemiBold") +
  tema() +   
  theme(legend.position = 'none',
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.background = element_rect(color = "#f0f5f7", linetype = "solid", size = 2))

```

diminuir width!

```{r}
gif_linhas <- grafico_linha +
  transition_reveal(1, Periodo) 
#  labs(subtitle = "{frame_along}") 

animate(gif_linhas, nframes = nrow(serie), height = 488, width = 668,
        renderer = gifski_renderer(loop = FALSE))


anim_save("rtn_sem_loop_v2.gif", animation = last_animation())

```

## Dados do estoque da dívida

```{r}
recurso_dpf_TT <- resource_show(id="0402cb77-5e4c-4414-966f-0e87d802a29a",
                             url="https://apickan.tesouro.gov.br/ckan")
download.file(recurso_dpf_TT$url, destfile = "./dpf.xlsx", mode = 'wb' )
tabela_div <- read_excel("dpf.xlsx", skip = 4)
```

```{r}
meses_red <- c("Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez")
which(meses_red == "Fev")

#         Mes_nome = factor(Mes, levels = meses_red)

dpf <- tabela_div %>%
  rename(rotulos = 1) %>%
  filter(str_detect(rotulos, "DPF EM PODER")) %>%
  select(-1) %>%
  gather(key = Mes_Ano, value = Valor) %>%
  separate(Mes_Ano, into = c("Mes", "Ano"), sep = "/") %>%
  filter(!is.na(Ano)) %>% # (3)
  mutate(Ano = as.integer(paste0('20', Ano)), # (4)
         Mes_num = match(Mes, meses_red),
         Periodo = as.Date(paste0(Ano, "-",
                                  if_else(Mes_num < 10, "0", ""), Mes_num, "-",
                                  "01")))
```

Atualizando os valores pelo IPCA

```{r}
ipca <- serie %>% select(Periodo, IPCA)

dpf <- dpf %>% 
  left_join(ipca) %>%
  mutate(Valor_ipca = Valor * IPCA)
  

```



```{r}
grafico_linha_dpf <- ggplot(dpf, aes(x = Periodo, y = Valor_ipca, color = TRUE, group = 1)) +
  geom_hline(yintercept = 0, color = '#f0f5f7', size = 1) +
  geom_line(size = 1) + 
  geom_point(size = 3, shape = 21, fill = "#f0f5f7") +
  scale_color_manual(values = c("TRUE" = "#1E4C7A")) +
  scale_x_date(date_breaks = "1 years", 
               date_labels = "%Y", 
               limits = c(as.Date("2006-01-01"), NA),
               expand = expand_scale(mult = c(.04, .04))) +
  coord_cartesian(clip = 'off') + 
  labs(x = NULL, y = NULL) +
  geom_text(aes(x = Periodo + 200,
                label = format(round(Valor_ipca/1000, 2), 
                                      big.mark = ".", 
                                      decimal.mark = ",")),
            size = 7, fontface = 'plain', family = "Open Sans SemiBold") +
  tema() +   
  theme(legend.position = 'none',
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.background = element_rect(color = "#f0f5f7", linetype = "solid", size = 2))
```

Animando

```{r}
gif_linhas_dpf <- grafico_linha_dpf +
  transition_reveal(1, Periodo) 
#  labs(subtitle = "{frame_along}") 

animate(gif_linhas_dpf, nframes = nrow(dpf), height = 488, width = 688,
        renderer = gifski_renderer(loop = FALSE))


anim_save("dpf_sem_loop_v2.gif", animation = last_animation())
```

