---
title: "OF x OSS"
author: "tiago"
date: "20 de dezembro de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lendo os dados

```{r}
dados_rec <- read_excel("Cópia de Estudo Albamaria _ Vinicius - Receita.xlsx", skip = 11)

glimpse(dados_rec)
View(dados_rec)
```

Identificando as naturezas de receitas que foram submetidas à DRU (na execução / arrecadação), segregando em DRU OF (detalhe fonte 980000) e DRU OSS (detalhe fonte 980001). O que acontece é que a parcela das receitas do OSS destinada à DRU já aparece na previsão como pertencente ao OF, e destinada à fonte 00.

```{r}
# pegando naturezas sujeitas à DRU
nat_dru <- dados_rec %>%
  filter(`Mês Lançamento` == "2018") %>%
  filter(`Fonte Detalhe` %in% c("980000", "980001")) %>%
  mutate(tipo_dru = case_when(
    `Fonte Detalhe` == "980000" ~ "DRU OF",
    `Fonte Detalhe` == "980001" ~ "DRU OSS"
  )) %>%
  select(`Natureza Receita Código Completo`, tipo_dru) %>%
  distinct()
```

